import { Inter } from 'next/font/google';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });
import styles from './layout.module.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function ProdutctsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav className={styles.nav}>
        <Link href='/products/women'>여성옷</Link>
        <Link href='./products/men'>남성옷</Link>
      </nav>
      <section className={styles.product}>{children}</section>
    </>
  );
}
